import type { Metadata } from 'next';
import { setRequestLocale } from 'next-intl/server';
import { MarketingHeader } from '@/components/MarketingHeader';
import { MarketingFooter } from '@/components/MarketingFooter';
import { pageMetadata } from '@/lib/seo';
import type { Locale } from '@/i18n/routing';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: Locale }>;
}): Promise<Metadata> {
  const { locale } = await params;
  return pageMetadata({
    title: 'Terms of Service — HearMe',
    description: 'The terms that govern your use of HearMe.',
    path: '/legal/terms',
    locale,
  });
}

export default async function TermsPage({ params }: { params: Promise<{ locale: Locale }> }) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <>
      <MarketingHeader />
      <main className="container max-w-3xl py-16">
        <h1 className="text-4xl font-bold">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: 17 June 2026</p>

        <div className="mt-8 space-y-6 text-muted-foreground">
          <p>
            These Terms govern your use of HearMe. By creating an account or using the service, you
            agree to these Terms. This document is a general template and not legal advice.
          </p>

          <Section title="The service">
            <p>
              HearMe is a voice-first AI companion for reflection and emotional support. It is not a
              therapist, counselor, or medical service, and must not be used for emergencies. If you are
              in crisis, contact your local emergency number or a crisis helpline.
            </p>
          </Section>

          <Section title="Eligibility & accounts">
            <p>
              You must be old enough to form a binding contract in your jurisdiction. You are responsible
              for activity under your account and for keeping your credentials secure.
            </p>
          </Section>

          <Section title="Acceptable use">
            <p>
              Don’t misuse HearMe — including attempting to disrupt the service, reverse-engineer it, use
              it unlawfully, or harm others. We may suspend accounts that violate these Terms.
            </p>
          </Section>

          <Section title="Plans, billing & minutes">
            <p>
              Free usage and paid plans are described on our pricing page. Paid plans renew until
              cancelled. Usage is metered in minutes; limits apply per your plan and may be enforced.
            </p>
          </Section>

          <Section title="AI-generated content">
            <p>
              Responses, reports, and insights are generated by AI and may be inaccurate or incomplete.
              They are for reflection only and are not professional advice. Use your own judgement.
            </p>
          </Section>

          <Section title="Disclaimers & liability">
            <p>
              HearMe is provided “as is” without warranties. To the maximum extent permitted by law, we
              are not liable for indirect or consequential damages arising from your use of the service.
            </p>
          </Section>

          <Section title="Changes">
            <p>We may update these Terms; continued use after changes means you accept the new Terms.</p>
          </Section>
        </div>
      </main>
      <MarketingFooter />
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="mb-2 text-xl font-semibold text-foreground">{title}</h2>
      {children}
    </section>
  );
}
